#profile
spring:
  profiles:
    active: dev
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/hl?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=Hongkong&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver


## web ##
server:  servlet:    context-path: /TestExample
  port: 3260


mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml




