#profile
spring:
  profiles:
    active: dev
  datasource:
    username: root
    password: root
    url: jdbc:mysql://10.10.10.233:3306/hl?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=Hongkong&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver  redis:    host: 10.118.3.1
    port: 6485
    password:


## web ##
server:  servlet:    context-path: /TestExample
  port: 3260


mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  
  




