#profile
spring:
  profiles:
    active: dev
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.1.3:3306/hl?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=Hongkong&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver  redis:    host: 10.118.3.1
    port: 6485
    password:


## web ##
server:  servlet:    context-path: /te
  port: 80

#mybatis
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  
#启动arthas编译调试跟踪问题 ，不写默认就是这个端口
arthas:  ip: 0.0.0.0
  http-port: 8563
  
  




